apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  DATASOURCE_URL: ZmlhcC1mYXN0Zm9vZC1hdXJvcmEtaW5zdGFuY2UtMS5jZjJzMDgyOHdldHkudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29t #jdbc:mysql://fiap-fastfood-aurora-instance-1.cf2s0828wety.us-east-1.rds.amazonaws.com:3306/fiapfastfood
  DATASOURCE_USERNAME: YWRtaW4= #admin
  DATASOURCE_PASSWORD: YWRtaW4xMjM= #admin123
  DATASOURCE_POOL-NAME: ZmlhcGZhc2Zvb2Q= #fiapfasfood
  DATASOURCE_MAXIMUM-POOL-SIZE: MTA= #10

  #TZ: QW1lcmljYS9TYW9fUGF1bG8= #America/Sao_Paulo
  #DATASOURCE_URL: amRiYzptYXJpYWRiOi8vZmFzdGZvb2QtZGItc2VydmljZTozMzA2L2ZpYXAtZmFzdGZvb2Q= #jdbc:mariadb://fastfood-db-service:3306/fiap-fastfood
  #DATASOURCE_USERNAME: ZmlhcF9wb3N0ZWNo #fiap_postech
  #DATASOURCE_PASSWORD: ZmlhcA== #fiap
  #DATASOURCE_POOL-NAME: ZmlhcC1mYXNmb29k #fiap-fasfood

#  DB_HOST: amRiYzptYXJpYWRiOi8vZmFzdG9vZC1kYjozMzA2L2ZpYXAtZmFzdGZvb2Q=
#  DB_USER: ZmlhcF9wb3N0ZWNo
#  DB_PASS: ZmlhcA==
#  MARIADB_DATABASE: ZmlhcC1mYXN0Zm9vZA==
#  MARIADB_ROOT_PASSWORD: cm9vdGZpYXA=
#  MARIADB_USER: ZmlhcF9wb3N0ZWNo
#  MARIADB_PASSWORD: ZmlhcA==